variables:
  PRODUCTION_CONTAINER_TAG: cms-prod

stages:
  - build
  - release
  - deploy

build:
  stage: build
  image: node
  script: 
    - sed -i 's/REACT_APP_API_BASE_URL=.*/REACT_APP_API_BASE_URL=/g' .env
    - yarn install
    - yarn build
  artifacts:
    expire_in: 15 minutes
    paths:
      - build
  only:
    refs:
      - master
      - refactor

release:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs: ["build"]
  only:
    refs:
      - master
      - refactor
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$PRODUCTION_CONTAINER_TAG

deploy_testing:
  stage: "deploy"
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - sed -i "s/{API_VERSION}/$(date +%Y%m%d%H%M%S)/g" kubernetes-deploy-dev.yml
    - sed -i "s/{SECRET}/${DOCKER_SECRET}/g" kubernetes-deploy-dev.yml
    - kubectl --kubeconfig="$K8S_DO_SECRET" apply -f kubernetes-deploy-dev.yml
  needs: ["release"]
  only:
    refs:
      - master
      - refactor
  when: manual

deploy_staging:
  stage: "deploy"
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - sed -i "s/{API_VERSION}/$(date +%Y%m%d%H%M%S)/g" kubernetes-deploy.yml
    - sed -i "s/{SECRET}/${DOCKER_SECRET}/g" kubernetes-deploy.yml
    - kubectl --kubeconfig="$K8S_DO_SECRET" apply -f kubernetes-deploy.yml
  needs: ["release"]
  only:
    refs:
      - master
      - refactor
  when: manual
