variables:
  PRODUCTION_CONTAINER_TAG: cms-prod
  DEBIAN_FRONTEND: noninteractive

stages:
  - build
  - release
  - deploy

build:
  stage: build
  image: node:14
  variables:
    GIT_SSL_NO_VERIFY: 1
  script: 
    - sed -i 's/REACT_APP_API_BASE_URL=.*/REACT_APP_API_BASE_URL=/g' .env
    - yarn install
    - yarn build
#    - |
#      if [ -z "`which git-quick-stats`" ]; then \
#      curl  -o "/bin/git-quick-stats" "https://github.com/arzzen/git-quick-stats/raw/master/git-quick-stats" && \
#      chmod +x "/bin/git-quick-stats"; \
#      fi && \
#      if [ -z "`which column`" ]; then \
#      apt update && apt install -y bsdmainutils python3; \
#      fi && \
#      if [ ! -z "$GIT_CONTRIBUTOR_COUNTER" ] && [ -f "$GIT_CONTRIBUTOR_COUNTER" ]; then \
#      git clone $CI_REPOSITORY_URL /tmp/clone; \
#      cd /tmp/clone ; \
#      python3 "$GIT_CONTRIBUTOR_COUNTER"; \
#      mv *.svg $CI_PROJECT_DIR/ ; \
#      cd $CI_PROJECT_DIR ; \
#      rm -rf /tmp/clone ; \
#      fi
  artifacts:
    expire_in: 15 minutes
    paths:
      - build
      - "*.svg"
  only:
    refs:
      - master

release:
  stage: release
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  needs: ["build"]
  only:
    refs:
      - master
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$PRODUCTION_CONTAINER_TAG

deploy_testing:
  stage: "deploy"
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - sed -i "s/{API_VERSION}/$(date +%Y%m%d%H%M%S)/g" kubernetes-deploy-dev.yml
    - sed -i "s/{SECRET}/${DOCKER_SECRET}/g" kubernetes-deploy-dev.yml
    - kubectl --kubeconfig="$K8S_DO_SECRET" apply -f kubernetes-deploy-dev.yml
  needs: ["release"]
  only:
    refs:
      - master
  when: manual

deploy_staging:
  stage: "deploy"
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - sed -i "s/{API_VERSION}/$(date +%Y%m%d%H%M%S)/g" kubernetes-deploy.yml
    - sed -i "s/{SECRET}/${DOCKER_SECRET}/g" kubernetes-deploy.yml
    - kubectl --kubeconfig="$K8S_DO_SECRET" apply -f kubernetes-deploy.yml
  needs: ["release"]
  only:
    refs:
      - master
  when: manual

deploy_production:
  stage: "deploy"
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - sed -i "s/{API_VERSION}/$(date +%Y%m%d%H%M%S)/g" kubernetes-prod.yml
    - sed -i "s/{SECRET}/${DOCKER_SECRET}/g" kubernetes-prod.yml
    - kubectl --kubeconfig="$K8S_DO_SECRET" apply -f kubernetes-prod.yml
  needs: ["release"]
  only:
    refs:
      - master
  when: manual
