apiVersion: v1
kind: Namespace
metadata:
  name: bayu-buana
---
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: "{SECRET}"
metadata:
  name: regcred
  namespace: bayu-buana
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: bayu-buana
  labels:
    app: frontend-service
spec:
  selector:
    matchLabels:
      app: frontend-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      hostPID: true
      containers:
        - image: registry.tog.co.id/bb/bayu-buana-cms:cms-prod
          name: frontend-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Asia/Jakarta
            - name: VERSION
              value: "{API_VERSION}"
          envFrom:
            - secretRef:
                name: master-service-config
      imagePullSecrets:
        - name: regcred
