apiVersion: v1
kind: Namespace
metadata:
  name: bayu-buana
---
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: "{SECRET}"
metadata:
  name: regcred
  namespace: bayu-buana
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-dev
  namespace: bayu-buana
  labels:
    app: frontend-service-dev
spec:
  selector:
    matchLabels:
      app: frontend-service-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-service-dev
    spec:
      hostPID: true
      containers:
        - image: registry.gitlab.com/kangmasvian/bb-backup:cms-prod
          name: frontend-service-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: Asia/Jakarta
            - name: VERSION
              value: "{API_VERSION}"
          envFrom:
            - secretRef:
                name: master-service-config-dev
      imagePullSecrets:
        - name: regcred
